// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurante_Repositories.DataContext;

#nullable disable

namespace Restaurante_Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241104212555_Atualiza_campo_data_atualizacao_aceita_null")]
    partial class Atualiza_campo_data_atualizacao_aceita_null
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurante_Borders.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurante");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dc9bc0d6-4266-4768-b4bd-d5959987ba44"),
                            DataCriacao = new DateTime(2024, 11, 4, 18, 25, 55, 137, DateTimeKind.Local).AddTicks(8004),
                            Endereco = "Rua dos Testes",
                            Nome = "Restaurante do Queres",
                            Site = "queres.com.br"
                        },
                        new
                        {
                            Id = new Guid("8f8f93be-baa1-4008-8236-e2ba9ccc8864"),
                            DataCriacao = new DateTime(2024, 11, 7, 18, 25, 55, 137, DateTimeKind.Local).AddTicks(8007),
                            Endereco = "Rua dos Desenvolvedores",
                            Nome = "Restaurante dos Desenvolvedores",
                            Site = "desenvolvedores.com.br"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
