// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurante_Repositories.DataContext;

#nullable disable

namespace Restaurante_Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241104212148_Adicionando_novo_campo")]
    partial class Adicionando_novo_campo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurante_Borders.Entities.Restaurante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurante");

                    b.HasData(
                        new
                        {
                            Id = new Guid("495d3582-6b96-4ede-a541-bfa8ea2f7604"),
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2024, 11, 4, 18, 21, 48, 480, DateTimeKind.Local).AddTicks(999),
                            Endereco = "Rua dos Testes",
                            Nome = "Restaurante do Queres",
                            Site = "queres.com.br"
                        },
                        new
                        {
                            Id = new Guid("b566998a-461f-4143-8f9f-fb6acd270a3d"),
                            DataAtualizacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataCriacao = new DateTime(2024, 11, 7, 18, 21, 48, 480, DateTimeKind.Local).AddTicks(1002),
                            Endereco = "Rua dos Desenvolvedores",
                            Nome = "Restaurante dos Desenvolvedores",
                            Site = "desenvolvedores.com.br"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
